# Generated by Django 3.1.4 on 2020-12-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201208_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
